### ISSUE TITLE
About Seminars@UTS resource

### ISSUE THREAD

**Issue by ghost** [layumi/layumi.github.io#1]
Thank you for sharing.
Could you upload slide in http://zdzheng.xyz/seminar.html to BaiduYun, because I can't access www.slideshare.net ?

**Comment by layumi** [comment]
Hi @gceboh 
Sorry for the late response. For the time being, we do not have a plan to move the slides to other places. Thanks a lot.

**Comment by ghost** [comment]
That's nothing. Thanks for reply!
